apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cluster-baseline-settings
resources:
- namespace.yaml
- resource-quota.yaml
- networkpolicy-denyall.yaml
- limit-range.yaml
- rbac.yaml
- secrets-store-csi/driver.yaml
- secrets-store-csi/keyvault-provider.yaml
- fim/fim-standin.yaml
- av/av-standin.yaml
- kured/kured.yaml
- osm/osm-crds.yaml
- osm/osm.yaml
secretGenerator:
  - name: osm-acr-instance
    type: Opaque
    literals:
      - name=REPLACE_ME_WITH_YOUR_ACRNAME
images:
- name: busybox
  newName: REPLACE_ME_WITH_YOUR_ACRNAME.azurecr.io/library/busybox
  newTag: 1.33.0
- name: docker.io/weaveworks/kured
  newName: REPLACE_ME_WITH_YOUR_ACRNAME.azurecr.io/weaveworks/kured
